---
- name: Install Packages
  hosts: all
  vars:
    packages:
      - curl
      - git
      - wget
      - tree
    facts: yes
  gather_facts: "{{ facts }}"

  tasks:
    - name: Install Packages
      when: 
        - ansible_distribution == "CentOS"
        - packages is defined
      yum:
        name: "{{ packages }}"
        state: latest